spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${DB_URL}           # Автоматически подставится из переменных
    username: ${DB_USERNAME} # окружения на Render
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false