spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${JDBC_DATABASE_URL} # Используем одну переменную, где всё уже есть
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false