rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
app:
  welcome-message: "Добро пожаловать в Hexlet Spring Blog!"