# src/main/resources/application-production.yml
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:postgresql://dpg-d35vrpqli9vc738puktg-a:5432/hexlet-spring-blog-db
    username: hexlet_spring_blog_db_user
    password: hGSHrVl0jKrRLtM2e9NZX6Rvvio12t75
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: false